apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: java-demo-api
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io 

spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: api
  project: default
  source:
    repoURL: https://gitlab.dspace.kt.co.kr/CNStudioD/CNStudio-sample-source/cnstudio-demo-ops.git
    path: java-demo-api/rolling
    targetRevision: main
    
  syncPolicy:
    automated:
      prune: true
      selfHeal: true