- name: "[ STEP 1 ] # 1. ===== Check Helm Installed ====="
  stat:
    path: /usr/local/bin/helm
  register: check_helm_exist

- debug:
    msg: "Helm already installed ..."
  when: check_helm_exist.stat.exists

- name: "[ STEP 1 ] # 2. ===== Helm install with archive ====="
  block:
    - name: "[ STEP 1 ] # 2-1. Create Temporary Directory"
      file:
        path: "{{TEMP_DIR_PATH}}"
        state: directory

    - name: "[ STEP 1 ] # 2-2. Unarchive"
      unarchive:
        src: archives/helm/helm-v3.15.0-linux-amd64.tar.gz
        dest: "{{TEMP_DIR_PATH}}"

    - name: "[ STEP 1 ] # 2-3. Move Helm Script"
      shell: 
        chdir: "{{TEMP_DIR_PATH}}"
        cmd: mv linux-amd64/helm /usr/local/bin/helm
  rescue:
    - name: "[ STEP 1 ] # 2. ***** ERROR OCCURED *****"
      debug:
        msg: "Unexpected error occured..."
  always:
    - name: "[ STEP 1 ] # 3. Clean Temporary Directory"
      file:
        path: "{{TEMP_DIR_PATH}}"
        state: absent
  become: true
  when: not check_helm_exist.stat.exists