- name: 8.1.0 Add Rancher helm repo
  ansible.builtin.shell:
    cmd: helm repo add rancher-stable https://releases.rancher.com/server-charts/stable

- name: 8.1.1 helm repo Update
  ansible.builtin.shell:
    cmd: helm repo update

- name: 8.1.2. Deploy rancher helm chart
  ansible.builtin.shell:
    cmd: |
      helm upgrade -i rancher rancher-stable/rancher \
      --namespace cattle-system --create-namespace \
      --set bootstrapPassword="admin" \
      --set tls=external \
      --set ingress.enabled=true \
      --set hostname=rancher.{{DOMAIN_NAME}}
  ignore_errors: yes
  tags:
    - catalog_rancherui

- name: 8.1.3. Wait for Rancher to be ready
  ansible.builtin.shell:
    cmd: |
      kubectl rollout status deployment rancher -n cattle-system
  register: rancher_status
  until: rancher_status.rc == 0
  retries: 30
  delay: 10
  tags:
    - catalog_rancherui

