- name: Download RKE2 install script
  get_url:
    url: https://get.rke2.io
    dest: /tmp/rke2-install.sh
    mode: '0755'

- name: Install RKE2 with sudo
  shell: sudo sh /tmp/rke2-install.sh

## RKE2 configuration file
- name: 3.7. Make necessary directories
  file:
    path: /etc/rancher/rke2
    state: directory

- name: 3.8. Add the content to the file
  copy:
    dest: /etc/rancher/rke2/config.yaml
    content: |
      write-kubeconfig-mode: "0644"
      tls-san:
        - {{ ALL_Servers[0].ip }}
      etcd-expose-metrics: true

## Run RKE2 Service 
- name: 3.9. Enable and start the rke2-server service
  ansible.builtin.systemd:
    name: rke2-server
    state: started
    enabled: true
  register: "check_rke2server_state"

- name: 3.10. Print rke2-server service status
  debug:
    msg: "{{ check_rke2server_state }}"

## Configure file
- name: 3.11. Make log directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - $HOME/.kube
    - "/home/{{ USER }}/.kube"

- name: 3.12. Set Up Kubeconfig
  copy:
    src: /etc/rancher/rke2/rke2.yaml
    dest: "{{ item }}"
    mode: 0600
    owner: "{{ USER }}"
    remote_src: yes
  with_items:
    - $HOME/.kube/config
    - "/home/{{ USER }}/.kube/config"

## File fetch
- name: 3.13. Copy node token from the master to the controller
  fetch:
    src: "/var/lib/rancher/rke2/server/token"
    dest: "{{ LOCAL_PATH.BASE }}/node-token/token"
    flat: yes

- name: 3.14. Copy kube config file from the master to the controller
  fetch:
    src: $HOME/.kube/config
    dest: "{{ LOCAL_PATH.BASE }}/kubeconfig"
    flat: yes

