---
- name: Make a sql file
  ansible.builtin.shell:
    cmd: |
      /usr/local/bin/kubectl exec -n psql psql-postgresql-ha-postgresql-0 -- bash -c "echo 'create table test (t1 int, t2 varchar(20), primary key(t1));
      insert into test values (1, \'test1\');
      insert into test values (2, \'test2\');' > /tmp/postgresql-test.sql";
  tags:
   - db-postgresql
   - make-sqlfile

- name: Create table
  ansible.builtin.shell:
    cmd: |
      /usr/local/bin/kubectl exec -n psql psql-postgresql-ha-postgresql-0 -- bash -c "PGPASSWORD='admin1234' psql -U postgres -d my_database < /tmp/postgresql-test.sql"
  tags:
   - db-postgresql
   - make-sqlfile
