###############버전 정보 확인 ############
LONGHORN_VERSION: 1.6.1
PROMETHEUS_VERSION: 56.8.2
OPENSEARCH_VERSION: 2.21.0
JAEGER_VERSION: 3.1.2
ISTIO_VERSION: 1.22.2
ARGOCD_VERSION: 7.0.0
MINIO_VERSION: 2024.07.04
VELERO_VERSION: 1.13.1
KEYCLOAK_VERSION: 21.2.2
RANCHERUI_VERSION: 2.8.5
GITLAB_VERSION: 7.11.2
JENKINS_VERSION:  5.4.3
NEUVECTOR_VERSION: 2.7.7
MARIADB_VERSION: 18.0.2
MYSQL_VERSION: 10.2.2
POSTGRESQL_VERSION: 14.2.7
KAFKA_VERSION: 29.3.4
REDIS_VERSION: 10.2.5

############### 설치 여부 확인 #############
DEPLOY_LONGHORN: true
DEPLOY_PROMETHEUS: true
DEPLOY_OPENSEARCH: false
DEPLOY_JAEGER: false
DEPLOY_ISTIO: false
DEPLOY_ARGOCD: false
DEPLOY_MINIO: false
DEPLOY_VELERO: false
DEPLOY_KEYCLOAK: false
DEPLOY_NODEJSCODE: false
DEPLOY_APIGATEWAY: false
DEPLOY_NODEJS: false
DEPLOY_JAVACODE: false
DEPLOY_PYTHONCODE: false
DEPLOY_RANCHERUI: true
DEPLOY_GITLAB: false
DEPLOY_GITLAB_RUNNER: false
DEPLOY_JENKINS: false
DEPLOY_NEUVECTOR: false
DEPLOY_MARIADB: false
DEPLOY_MYSQL: false
DEPLOY_POSTGRESQL: false
DEPLOY_KAFKA: false
DEPLOY_REDIS: false

