###############버전 정보 확인 ############
LONGHORN_VERSION: 1.6.1
PROMETHEUS_VERSION: 56.8.2
OPENSEARCH_VERSION: 2.21.0
JAEGER_VERSION: 3.1.2
ISTIO_VERSION: 1.22.2
ARGOCD_VERSION: 7.5.0
MINIO_VERSION: 2024.07.04
VELERO_VERSION: 1.13.1
KEYCLOAK_VERSION: 21.2.2
RANCHERUI_VERSION: 2.8.5
GITLAB_VERSION: 7.11.2
JENKINS_VERSION:  5.4.3
NEUVECTOR_VERSION: 2.7.7
MARIADB_VERSION: 18.0.2
MYSQL_VERSION: 10.2.2
POSTGRESQL_VERSION: 14.2.7
KAFKA_VERSION: 29.3.4
REDIS_VERSION: 10.2.5

############### 설치 여부 확인 #############
DEPLOY_LONGHORN: true
DEPLOY_PROMETHEUS: true
DEPLOY_OPENSEARCH: true
DEPLOY_JAEGER: true
DEPLOY_ISTIO: true
DEPLOY_ARGOCD: true
DEPLOY_MINIO: true
DEPLOY_VELERO: true
DEPLOY_KEYCLOAK: true
DEPLOY_NODEJSCODE: false
DEPLOY_APIGATEWAY: false
DEPLOY_NODEJS: true
DEPLOY_JAVACODE: true
DEPLOY_PYTHONCODE: true
DEPLOY_RANCHERUI: true
DEPLOY_GITLAB: true
DEPLOY_GITLAB_RUNNER: true
DEPLOY_JENKINS: true
DEPLOY_NEUVECTOR: true
DEPLOY_MARIADB: true
DEPLOY_MYSQL: true
DEPLOY_POSTGRESQL: true
DEPLOY_KAFKA: true
DEPLOY_REDIS: true

