---
########## hosts info #################
HOST_IP: "{{ansible_host}}"

LOCAL_USER_HOME: "{{ LOCAL_PATH.BASE }}"

########## glb_ingress_namespace #################
GLB_INGRESS_NAMESPACE: "kube-system"

##########demo-project##############
DEMO_OPS_REPO_URL: "https://gitlab.dspace.kt.co.kr/CNStudioD/CNStudio-sample-source/cnstudio-demo-ops.git"
DEMO_OPS_REPO_PRIVATE: "N"
DEMO_OPS_GIT_USER: "user-id"
DEMO_OPS_GIT_SECRET: ""

######### node-api #################
NODE_API_NAMESPACE: "nodeapi"
NODE_API_INGRESS_HOST: "node-api.cnstudio.com"
NODE_API_ARGOCD_DEPLOY_TYPE: "rolling" ## default: rolling  deploy_type: rolling, bluegreen, canary
NODE_API_ARGOCD_TARGET_REVISION: "main" ## default: main ,  revision: main, pinpoint

########## argocd #################
ARGOCD_HOST: "10.71.163.70:30800"  ## TODO 아르고 호스트  주소는 변수 처리 CN 어드민화면에서 변수 파라미터로 적용 가능 여부 확인 필요
ARGOCD_NEW_PASSWORD: "admin1234"
