
# ! Fixed Values
USER_HOME: /home/{{ USER }}
TEMP_DIR_PATH: "{{USER_HOME}}/tmp2"
# !

NEXUS_REGISTRY: none

### ! GitLab Helm Chart Configuraton
# ? GitLab Helm Chart Version
GITLAB_HELM_REPOSITORY_URL: https://charts.gitlab.io/
GITLAB_DEFAULT_HELM_VERSION: "7.11.2"
GITLAB_RUNNER_DEFAULT_HELM_VERSION: "0.64.0"

GITLAB_DEFAULT_HELM_VALUES:
  CERTMANAGER_ISSUER:
    EMAIL: example@example.com
### !

### ! GitLab Installation Metadata
# ? GitLab Release Label
GITLAB_DEFAULT_METADATA_RELEASE_LABEL: gitlab

# ? GitLab Install Target Namespace
GITLAB_DEFAULT_METADATA_NAMESPACE: gitlab
### !

### ! GitLab Root Account Configuration
# ? GitLab Root Account Password
GITLAB_DEFAULT_ACCOUNT_ROOT_PASSWORD: password

# ? GitLab Root Personal Access Token 
GITLAB_DEFAULT_ACCOUNT_ROOT_ACCESS_TOKEN_NAME: InitializeToken
GITLAB_DEFAULT_ACCOUNT_ROOT_ACCESS_TOKEN_VALUE: initialize
### !

### ! GitLab Persistent Volume Configuration
## * Global Configuration
# ? GitLab Global Persistent Volume Location Node Selector Configuration
GITLAB_PERSISTENT_GLOBAL_STORAGE_NODE_AFFINITY_KEY: kubernetes.io/hostname
## *

# ? Already GitLab Data Volume Exist
GITLAB_DEFAULT_PERSISTENT_EXIST: no

# ? GitLab Installation with Sample Source Code
GITLAB_DEFAULT_PERSISTENT_INCLUDE_SAMPLE_SOURCE: yes

# ? GitLab Data Volume Path (Root)
GITLAB_DEFAULT_PERSISTENT_ROOT_STORAGE_MOUNT_PATH: /data/gitlab-volume

## * GitLab Data Volume Configuration (Redis)
# ? GitLab Redis Node Selector Configuration
GITLAB_PERSISTENT_REDIS_STORAGE_NODE_AFFINITY_KEY: "{{GITLAB_PERSISTENT_GLOBAL_STORAGE_NODE_AFFINITY_KEY}}"

# ? GitLab Redis Node Selector Configuration
GITLAB_DEFAULT_PERSISTENT_REDIS_STORAGE_NODE_SELECTOR_KEY: "{{GITLAB_PERSISTENT_DEFAULT_STORAGE_NODE_SELECTOR_KEY}}"
GITLAB_DEFAULT_PERSISTENT_REDIS_STORAGE_NODE_SELECTOR_VALUE: "{{GITLAB_PERSISTENT_DEFAULT_STORAGE_NODE_SELECTOR_VALUE}}"

# ? GitLab Redis Volume Configuration
GITLAB_PERSISTENT_REDIS_STORAGE_NAME: "{{GITLAB_METADATA_NAMESPACE}}-gitlab-redis-pv"
GITLAB_PERSISTENT_REDIS_STORAGE_CLASS_NAME: "longhorn"

GITLAB_DEFAULT_PERSISTENT_REDIS_STORAGE_MOUNT_PATH: "{{GITLAB_PERSISTENT_ROOT_STORAGE_MOUNT_PATH}}"
GITLAB_DEFAULT_PERSISTENT_REDIS_STORAGE_SIZE: 10Gi
## *

## * GitLab Data Volume Configuration (Gitaly)
# ? GitLab Gitaly Node Selector Configuration
GITLAB_PERSISTENT_GITALY_STORAGE_NODE_AFFINITY_KEY: "{{GITLAB_PERSISTENT_GLOBAL_STORAGE_NODE_AFFINITY_KEY}}"

# ? GitLab Gitaly Node Selector Configuration
GITLAB_DEFAULT_PERSISTENT_GITALY_STORAGE_NODE_SELECTOR_KEY: "{{GITLAB_PERSISTENT_DEFAULT_STORAGE_NODE_SELECTOR_KEY}}"
GITLAB_DEFAULT_PERSISTENT_GITALY_STORAGE_NODE_SELECTOR_VALUE: "{{GITLAB_PERSISTENT_DEFAULT_STORAGE_NODE_SELECTOR_VALUE}}"

# ? GitLab Gitaly Volume Configuration
GITLAB_PERSISTENT_GITALY_STORAGE_NAME: "{{GITLAB_METADATA_NAMESPACE}}-gitlab-gitaly-pv"
GITLAB_PERSISTENT_GITALY_STORAGE_CLASS_NAME: "longhorn"

GITLAB_DEFAULT_PERSISTENT_GITALY_STORAGE_MOUNT_PATH: "{{GITLAB_PERSISTENT_ROOT_STORAGE_MOUNT_PATH}}"
GITLAB_DEFAULT_PERSISTENT_GITALY_STORAGE_SIZE: 10Gi
## *

## * GitLab Data Volume Configuration (Postgresql)
# ? GitLab Postgresql Node Selector Configuration
GITLAB_PERSISTENT_POSTGRESQL_STORAGE_NODE_AFFINITY_KEY: "{{GITLAB_PERSISTENT_GLOBAL_STORAGE_NODE_AFFINITY_KEY}}"

# ? GitLab Postgresql Node Selector Configuration
GITLAB_DEFAULT_PERSISTENT_POSTGRESQL_STORAGE_NODE_SELECTOR_KEY: "{{GITLAB_PERSISTENT_DEFAULT_STORAGE_NODE_SELECTOR_KEY}}"
GITLAB_DEFAULT_PERSISTENT_POSTGRESQL_STORAGE_NODE_SELECTOR_VALUE: "{{GITLAB_PERSISTENT_DEFAULT_STORAGE_NODE_SELECTOR_VALUE}}"

# ? GitLab Postgresql Auth Configuration
GITLAB_DEFAULT_PERSISTENT_POSTGRESQL_ADMIN_PASSWORD: admin
GITLAB_DEFAULT_PERSISTENT_POSTGRESQL_USER_PASSWORD: user

# ? GitLab Postgresql Volume Configuration
GITLAB_PERSISTENT_POSTGRESQL_STORAGE_NAME: "{{GITLAB_METADATA_NAMESPACE}}-gitlab-postgresql-pv"
GITLAB_PERSISTENT_POSTGRESQL_STORAGE_CLASS_NAME: "longhorn"

GITLAB_DEFAULT_PERSISTENT_POSTGRESQL_STORAGE_MOUNT_PATH: "{{GITLAB_PERSISTENT_ROOT_STORAGE_MOUNT_PATH}}"
GITLAB_DEFAULT_PERSISTENT_POSTGRESQL_STORAGE_SIZE: 10Gi
## *

## * GitLab Data Volume Configuration (MinIO)
# ? GitLab MinIO Node Selector Configuration
GITLAB_PERSISTENT_MINIO_STORAGE_NODE_AFFINITY_KEY: "{{GITLAB_PERSISTENT_GLOBAL_STORAGE_NODE_AFFINITY_KEY}}"

# ? GitLab MinIO Node Selector Configuration
GITLAB_DEFAULT_PERSISTENT_MINIO_STORAGE_NODE_SELECTOR_KEY: "{{GITLAB_PERSISTENT_DEFAULT_STORAGE_NODE_SELECTOR_KEY}}"
GITLAB_DEFAULT_PERSISTENT_MINIO_STORAGE_NODE_SELECTOR_VALUE: "{{GITLAB_PERSISTENT_DEFAULT_STORAGE_NODE_SELECTOR_VALUE}}"

# ? GitLab MinIO Volume Configuration
GITLAB_PERSISTENT_MINIO_STORAGE_NAME: "{{GITLAB_METADATA_NAMESPACE}}-gitlab-minio-pv"
GITLAB_PERSISTENT_MINIO_STORAGE_CLASS_NAME: "longhorn"

GITLAB_DEFAULT_PERSISTENT_MINIO_STORAGE_MOUNT_PATH: "{{GITLAB_PERSISTENT_ROOT_STORAGE_MOUNT_PATH}}"
GITLAB_DEFAULT_PERSISTENT_MINIO_STORAGE_SIZE: 10Gi
## *
### !
